apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ch11778z5-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ch11778z5-nodejs 
  name: ch11778z5-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ch11778z5-nodejs 
